### ISSUE TITLE
Format issue on Docker Compose page

### ISSUE THREAD

**Issue by t73liu** [docker/docker.github.io#11979]
File: [get-started/08_using_compose.md](https://docs.docker.com/get-started/08_using_compose/)

![Screenshot_2020-12-24 Using Docker Compose](https://user-images.githubusercontent.com/5432907/103103854-f7195700-45f1-11eb-8274-7425b23d2810.png)

**Comment by sudo-bmitch** [comment]
Thanks for the report. I believe this is fixed in #11975.

**Comment by t73liu** [comment]
I still see the issue in the PR's attached preview: https://deploy-preview-11975--docsdocker.netlify.app/get-started/08_using_compose/#defining-the-app-service

**Comment by sudo-bmitch** [comment]
Woops, wrong PR, (I was trying to go from memory as I went from PR to issue in the mobile interface).

This is fixed in #11947 and can be seen in the preview at https://deploy-preview-11947--docsdocker.netlify.app/get-started/08_using_compose/

**Comment by thaJeztah** [comment]
https://github.com/docker/docker.github.io/pull/11947 was merged, and will be published on docs.docker.com soon
