### ISSUE TITLE
404 at /samples/jetty/

### ISSUE THREAD

**Issue by Level60Warlock** [docker/docker.github.io#4167]
URL: /samples/jetty/
Appears that the correct locations should be /samples/library/jetty
FWIW, looks like a number of other samples have the additional level of /library in the path:
/samples/composer --> /samples/library/composer
/samples/mongo --> /samples/library/mongo
/samples/maven --> /samples/library/maven
/samples/httpd --> /samples/library/httpd
Etc...

**Comment by Artur-A** [comment]
The same for `/samples/php` --> `/samples/library/php`

**Comment by johndmulhausen** [comment]
Fixed by #4195 (will be live in 15 minutes)

**Comment by Level60Warlock** [comment]
@johndmulhausen  - Most are working, but still seeing a 502 response for some, such as Jetty, PHP, and Tomee:
https://docs.docker.com/samples/library/jetty/
https://docs.docker.com/samples/library/php/
https://docs.docker.com/samples/library/tomee/
