### ISSUE TITLE
Upgrade DTR to 2.6 link broken

### ISSUE THREAD

**Issue by Binder7777** [docker/docker.github.io#9645]
### Problem description

The link in docker documentation for "Upgrade DTR to 2.6" is giving a 404

The link is https://docs.docker.com/ee/dtr/2.6/guides/admin/upgrade 

and is in the documentation for almost any upgrade except 2.5

I need to upgrade my docker DTR to 2.6

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/ee/dtr/2.6/guides/admin/upgrade

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/ee/dtr/2.6/guides/admin/upgrade

**Comment by Potapy4** [comment]
@Binder7777  It looks like you are looking for this: https://docs.docker.com/datacenter/dtr/2.6/guides/admin/upgrade

**Comment by Binder7777** [comment]
Yes, thanks for putting it back out there!

**Comment by Binder7777** [comment]
Not sure if I need to open another ticket but this page referenced from the link you provided is not working.

https://docs.docker.com/reference/dtr/2.6/cli/

[cid:image001.png@01D584D8.6EB9A440]

**Comment by Binder7777** [comment]
Sorry right url, but wrong location.

[cid:image002.png@01D584D9.490483E0]

From: Leonard, William
Sent: Thursday, October 17, 2019 10:49 AM
To: 'docker/docker.github.io' <reply@reply.github.com>; docker/docker.github.io <docker.github.io@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [EXT] Re: [docker/docker.github.io] Upgrade DTR to 2.6 link broken (#9645)

Not sure if I need to open another ticket but this page referenced from the link you provided is not working.

https://docs.docker.com/reference/dtr/2.6/cli/

[cid:image003.png@01D584D9.490483E0]

**Comment by lena-larionova** [comment]
Fixed in https://github.com/docker/docker.github.io/pull/9658

**Comment by Binder7777** [comment]
I’m sorry, but what does that mean?  It still does not work for me.

**Comment by lena-larionova** [comment]
> I’m sorry, but what does that mean? It still does not work for me.

Try clearing your browser's cache or do a hard refresh on the upgrade page, that might work. Otherwise, this is the working link for the DTR 2.6 upgrade: https://docs.docker.com/datacenter/dtr/2.6/guides/admin/upgrade/

And it's fixed on the current upgrade page (https://docs.docker.com/ee/dtr/admin/upgrade/).
